package com.mycompany.myapp.domain.enumeration;

/**
 * The Filieres enumeration.
 */
public enum Filieres {
    AGRICULTURE,
    ELEVAGE,
    MINESETCARRIERES,
    BATIMENTSETTRAVAUXPUBLICS,
    MECANIQUE,
    MENUISERIE,
    AGROALIMENTAIRE,
    ELECTROTECHNIQUE_ELECTRONIQUE_ENERGETIQUE,
    STRUCTUREMETALLIQUE,
    ECONOMIEETGESTION,
    COMMERCELOGISTIQUE,
    INFORMATIQUEETNUMERIQUE,
    SANTEBIOLOGIECHIMIE,
    AUTRE,
}
