package com.mycompany.myapp.domain.enumeration;

/**
 * The SANTEBIOLOGIECHIMIE enumeration.
 */
public enum SANTEBIOLOGIECHIMIE {
    AGENT_DE_SANTE_COMMUNAUTAIRE,
    AGENT_DE_STERILISATION_EN_MILIEU_HOSPITALIER,
    ANALYSE_BIOLOGIQUE,
    AUXILIAIRE_AMBULANCIER,
    BRANCARDIER,
    DIETETIQUE_NUTRITION_BTS_APC,
    HYGIENE_SECURITE_ENVIRONNEMENT,
    SANTE_HYGIENE,
    TECHNICIEN_DE_SURFACE_EN_MILIEU_HOSPITALIER,
    AUTRE,
}
