export enum Filieres {
  AGRICULTURE = 'AGRICULTURE',

  ELEVAGE = 'ELEVAGE',

  MINESETCARRIERES = 'MINESETCARRIERES',

  BATIMENTSETTRAVAUXPUBLICS = 'BATIMENTSETTRAVAUXPUBLICS',

  MECANIQUE = 'MECANIQUE',

  MENUISERIE = 'MENUISERIE',

  AGROALIMENTAIRE = 'AGROALIMENTAIRE',

  ELECTROTECHNIQUE_ELECTRONIQUE_ENERGETIQUE = 'ELECTROTECHNIQUE_ELECTRONIQUE_ENERGETIQUE',

  STRUCTUREMETALLIQUE = 'STRUCTUREMETALLIQUE',

  ECONOMIEETGESTION = 'ECONOMIEETGESTION',

  COMMERCELOGISTIQUE = 'COMMERCELOGISTIQUE',

  INFORMATIQUEETNUMERIQUE = 'INFORMATIQUEETNUMERIQUE',

  SANTEBIOLOGIECHIMIE = 'SANTEBIOLOGIECHIMIE',

  AUTRE = 'AUTRE',
}
