export enum FonctionPersAd {
  PROVISEUR = 'PROVISEUR',

  SECRETAIRE = 'SECRETAIRE',

  DIRECTEURDESETUDES = 'DIRECTEURDESETUDES',

  AUDITEUR_INTERNE = 'AUDITEUR_INTERNE',

  CHEF_DESTRAVAUX = 'CHEF_DESTRAVAUX',

  COMPTABLE_DESMATIERES = 'COMPTABLE_DESMATIERES',

  INTENDANT = 'INTENDANT',

  RESPONSABLE_CELLULE_PEDAGOGIQUE = 'RESPONSABLE_CELLULE_PEDAGOGIQUE',

  SURVEIILLANT = 'SURVEIILLANT',

  SURVEILLANT_SIMPLE = 'SURVEILLANT_SIMPLE',

  INFIRMIER = 'INFIRMIER',

  COMPTABLE = 'COMPTABLE',

  ASSISTANTE_SOCIAL = 'ASSISTANTE_SOCIAL',

  ANIMATEUR_CULTUREL = 'ANIMATEUR_CULTUREL',

  BIBLIOTHECAIRE = 'BIBLIOTHECAIRE',

  AUTRE = 'AUTRE',
}
