export enum Provenance {
  ENTREPRISE = 'ENTREPRISE',

  ONG = 'ONG',

  ORGANISATION_SOCIALE = 'ORGANISATION_SOCIALE',

  ORGANISATION_PROFESSIONNELLE = 'ORGANISATION_PROFESSIONNELLE',

  PATRONAT = 'PATRONAT',

  APE = 'APE',

  SYNDICAT = 'SYNDICAT',

  COLLECTIVITE_TERRITORIALE = 'COLLECTIVITE_TERRITORIALE',

  SERVICE_DECONCENTRE = 'SERVICE_DECONCENTRE',

  COOPERATION_DECENTRALISEE = 'COOPERATION_DECENTRALISEE',

  AUTRES = 'AUTRES',
}
