export enum SANTEBIOLOGIECHIMIE {
  AGENT_DE_SANTE_COMMUNAUTAIRE = 'AGENT_DE_SANTE_COMMUNAUTAIRE',

  AGENT_DE_STERILISATION_EN_MILIEU_HOSPITALIER = 'AGENT_DE_STERILISATION_EN_MILIEU_HOSPITALIER',

  ANALYSE_BIOLOGIQUE = 'ANALYSE_BIOLOGIQUE',

  AUXILIAIRE_AMBULANCIER = 'AUXILIAIRE_AMBULANCIER',

  BRANCARDIER = 'BRANCARDIER',

  DIETETIQUE_NUTRITION_BTS_APC = 'DIETETIQUE_NUTRITION_BTS_APC',

  HYGIENE_SECURITE_ENVIRONNEMENT = 'HYGIENE_SECURITE_ENVIRONNEMENT',

  SANTE_HYGIENE = 'SANTE_HYGIENE',

  TECHNICIEN_DE_SURFACE_EN_MILIEU_HOSPITALIER = 'TECHNICIEN_DE_SURFACE_EN_MILIEU_HOSPITALIER',

  AUTRE = 'AUTRE',
}
