export enum TypeO {
  CONSEIL_ADMINISTRATION = 'CONSEIL_ADMINISTRATION',

  CONSEIL_ETABLISSEMENT = 'CONSEIL_ETABLISSEMENT',

  CONSEIL_PEDAGOGIQUE = 'CONSEIL_PEDAGOGIQUE',

  COMITE_GESTION = 'COMITE_GESTION',

  AUTRES = 'AUTRES',
}
