export enum TypeDepense {
  INVESTISSEMENT = 'INVESTISSEMENT',

  PERSONNEL = 'PERSONNEL',

  BIENS_ET_SERVICES = 'BIENS_ET_SERVICES',

  TRANSFERTS_COURANTS = 'TRANSFERTS_COURANTS',

  AUTRES = 'AUTRES',
}
