export enum TypeB {
  PERSONNEL_APPOINT = 'PERSONNEL_APPOINT',

  PERSONNEL_ADMINISTRATIF = 'PERSONNEL_ADMINISTRATIF',

  RENFORCEMENT_CAPACITE = 'RENFORCEMENT_CAPACITE',

  PERSONNE_RESSOURCE = 'PERSONNE_RESSOURCE',

  SOCIAUX = 'SOCIAUX',

  INFRASTRUCTURE = 'INFRASTRUCTURE',

  EQUIPEMENT = 'EQUIPEMENT',

  FORMATION = 'FORMATION',

  INFRASTRUCTURES = 'INFRASTRUCTURES',

  AUTRES = 'AUTRES',
}
